### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'word-vectors/small-paragram.txt'

### ISSUE THREAD

**Issue by loveJasmine** [nmrksic/neural-belief-tracker#3]
mldl@ub1604:~/ub16_prj/neural-belief-tracker$ bash train.sh 
/usr/local/lib/python2.7/dist-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Vectors not there, downloading small Paragram and putting it there.
--2018-08-29 15:26:55--  https://mi.eng.cam.ac.uk/~nm480/prefix_paragram.txt
Connecting to 127.0.0.1:39739... connected.
Proxy request sent, awaiting response... 403 Forbidden
2018-08-29 15:26:58 ERROR 403: Forbidden.

mv: cannot stat 'prefix_paragram.txt': No such file or directory
Loading pretrained word vectors from word-vectors/small-paragram.txt - treating english as the primary language.
Traceback (most recent call last):
  File "code/nbt.py", line 1940, in <module>
    main()              
  File "code/nbt.py", line 1887, in main
    NBT = NeuralBeliefTracker(config_filepath)
  File "code/nbt.py", line 1624, in __init__
    word_vectors = load_word_vectors(word_vector_destination, primary_language=language)
  File "code/nbt.py", line 1110, in load_word_vectors
    f = codecs.open(file_destination, 'r', 'utf-8') 
  File "/usr/lib/python2.7/codecs.py", line 896, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: 'word-vectors/small-paragram.txt'
mldl@ub1604:~/ub16_prj/neural-belief-tracker$

**Comment by nmrksic** [comment]
My Cambridge account's been killed. Updated with dropbox link, closing issue.
